/**
 * @file src/middleware.ts
 * Next.js Edge Middleware — 国际化路由拦截 / i18n route interception
 *
 * 作用 / Purpose:
 *   在每次请求到达页面之前运行，自动将无语言前缀的 URL 重定向到默认语言 URL。
 *   Runs before every page request. Automatically redirects prefix-less URLs
 *   to the default locale URL.
 *
 * 示例 / Example:
 *   访问 / → 重定向到 /zh
 *   访问 /product → 重定向到 /zh/product
 *   访问 /en/product → 直接放行（已有语言前缀）
 *
 * 调用时机 / When called:
 *   Next.js 在路由匹配之前自动调用，不需要手动引用。
 *   Automatically called by Next.js before route matching — no manual import needed.
 */
import createMiddleware from "next-intl/middleware";
import { routing } from "./i18n/routing";

/**
 * next-intl 生成的中间件实例
 * Middleware instance generated by next-intl
 * 内部逻辑 / Internal logic:
 *   1. 检测请求 URL 中的 locale 前缀
 *   2. 若缺失则重定向到 defaultLocale（"zh"）
 *   3. 若存在但不在 locales 列表中则 404
 */
export default createMiddleware(routing);

/**
 * matcher 配置告诉 Next.js 哪些路径需要走 Middleware
 * matcher config tells Next.js which paths should run through this Middleware
 *
 * 规则 / Rule:
 *   排除 /api/*、/_next/*、/_vercel/*、以及所有带文件扩展名的静态文件（如 .png、.ico）
 *   Excludes /api/*, /_next/*, /_vercel/*, and static files with extensions (e.g. .png, .ico)
 */
export const config = {
  matcher: ["/((?!api|_next|_vercel|.*\\..*).*)"],
};
